import Head from 'next/head';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const Dashboard = dynamic(() => import('../src/components/Dashboard'), {
  ssr: false,
  loading: () => <h2>Loading...</h2>,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Dashboard />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
